export default function ItemEntry(props) {
  return (
    <div>
      <a
        href={props.url}
        target="_blank"
        rel="noreferrer"
        data-testid="LinkButton"
        class="buttony"
        height="auto"
      >
        <div>
          <div
            data-testid="LinkThumbnail"
            type="CLASSIC"
            class="thumby"
          >
            <img
              data-testid="LinkThumbnailImage"
              src={props.thumbimg}
              class="otherthumby"
            />
          </div>
          <p>
            {props.content}
          </p>
        </div>
      </a>
    </div>
  )
}